state: 'python-vicuna-7b.state.json'

fitness:
  FitnessCanAiCode:
    language: 'both'
    input: 'can-ai-code/results/prepare_junior-dev_python_Vicuna-1p1.ndjson'
    interviewer: 'python3 -u can-ai-code/interview-llamacpp.py --ssh miner --threads 4 --model /home/miner/ai/models/v3/ggml-vicuna-7b-1.1-q5_0.bin'
    samples: 2
    evaluate: 'python3 can-ai-code/evaluate.py'
    paramdir: 'python-vicuna-7b/'
    paramprefix: 'vicuna-7b'
    resultglob: 'can-ai-code/results/interview_junior-dev_python_Vicuna-1p1_none_vicuna-7b-{id}_ggml-vicuna-7b-1.1-q5_0_*.ndjson' 

population:
  initial:
    - initial: { }
    - mutate: { current: 0, iter: 2 }
    - mutate: { current: 1, iter: 2 }
    - mutate: { current: 2, iter: 2 }
    - mutate: { current: 3, iter: 2 }

  selection:
    - pick: { top: 0 }
    - pick: { top: 1 } 
    - mutate: { top: 0, iter: 1 }
    - mutate: { top: 0, iter: 5 }
    - breed: { mom: { top: 0 }, dad: { top: 1 } }

params:
- parameter: temperature
  value: 1.0
  mutation_type: geometric
  mutation_value:
    uniform: [0.9, 1.05]
  min_value: 0.0

- parameter: repetition_penalty
  value: 1.176
  mutation_type: geometric
  mutation_value:
    uniform: [0.95, 1.05]
  min_value: 1.0

- parameter: top_k
  value: 1
  mutation_type: additive
  mutation_value:
    uniform: [-1, 1]
  min_value: 1

- parameter: top_p
  value: 1.0
  mutation_type: geometric
  mutation_value:
    uniform: [0.9, 1.1]
  max_value: 1.0

- parameter: repeat_last_n
  value: 256
  mutation_type: additive
  mutation_value:
    uniform: [-32, 8]
  min_value: 8
